### ISSUE TITLE
STM32F105RBT6 SRAM entry point

### ISSUE THREAD

**Issue by VR555** [CTXz/stm32f1-picopwner#16]
Hi, what might be wrong?
```
Debug probe already connected, please disconnect the debug probe for now
Device already connected to /dev/ttyACM0
Please press the reset button on the Pi Pico or reconnect it to ensure a clean state
Waiting for Pi Pico to be connected... (Looking for /dev/ttyACM0)
Device connected to serial port /dev/ttyACM0
Waiting for debug probe to be connected...
Debug probe connected to STM32F1 target
STM32F1 target is confirmed to be read protected
Traceback (most recent call last):
  File "/home/einar/pico/stm32f1-picopwner/dump.py", line 442, in <module>
    sram_entry_point = get_sram_entry_point()
  File "/home/einar/pico/stm32f1-picopwner/dump.py", line 284, in get_sram_entry_point
    raise Exception("Could not determine SRAM entry point\nopenocd output: " + line)
Exception: Could not determine SRAM entry point
openocd output: xPSR: 0x01000000 pc: 0x1fffe9c0 msp: 0x20000ff0
```

**Comment by CTXz** [comment]
Appears to be simmlar to https://github.com/CTXz/stm32f1-picopwner/issues/15#issuecomment-1908447070. Please verify your BOOT1 pin is being pull up properly.

**Comment by CTXz** [comment]
Since this issue has been inactive for a prolonged period of time now, I'll be closing it. I'll gladly reopen it if necessary.
